-- =====================================================
-- BASE DE DATOS - SALON DE BELLEZA - SUPABASE/POSTGRESQL
-- Tablas, datos iniciales, indices y vistas
-- =====================================================
-- Ejecutar en un proyecto Supabase nuevo desde SQL Editor.
-- No incluye DROP/CREATE DATABASE porque Supabase ya crea la base.

CREATE TABLE administrador (
 id_admin INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 usuario VARCHAR(50) UNIQUE NOT NULL,
 correo VARCHAR(120) UNIQUE,
 password VARCHAR(255) NOT NULL,
 reset_token VARCHAR(64),
 reset_expires_at TIMESTAMP
);

CREATE TABLE clientes (
 id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 telefono VARCHAR(20) NOT NULL,
 correo VARCHAR(120),
 direccion TEXT,
 provincia VARCHAR(80),
 canton VARCHAR(80),
 distrito VARCHAR(80),
 fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contacto_mensajes (
 id_mensaje INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(120) NOT NULL,
 telefono VARCHAR(30) NOT NULL,
 correo VARCHAR(120) NOT NULL,
 asunto VARCHAR(150) NOT NULL,
 mensaje TEXT NOT NULL,
 ip VARCHAR(45),
 creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categorias (
 id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 descripcion TEXT,
 tipo VARCHAR(20) NOT NULL DEFAULT 'Producto' CHECK (tipo IN ('Producto', 'Servicio', 'Ambos')),
 estado VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo'))
);

CREATE TABLE productos (
 id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_categoria INTEGER NOT NULL REFERENCES categorias(id_categoria),
 codigo VARCHAR(30) UNIQUE,
 nombre VARCHAR(150) NOT NULL,
 descripcion TEXT,
 precio NUMERIC(10,2) NOT NULL,
 precio_oferta NUMERIC(10,2),
 destacado BOOLEAN DEFAULT FALSE,
 stock INTEGER DEFAULT 0,
 imagen VARCHAR(255),
 estado VARCHAR(20) NOT NULL DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'Agotado', 'Descontinuado')),
 fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ofertas (
 id_oferta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_producto INTEGER NOT NULL REFERENCES productos(id_producto) ON DELETE CASCADE,
 porcentaje NUMERIC(5,2),
 precio_oferta NUMERIC(10,2),
 fecha_inicio DATE,
 fecha_fin DATE,
 activa BOOLEAN DEFAULT TRUE
);

CREATE TABLE servicios (
 id_servicio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(150),
 categoria VARCHAR(80),
 descripcion TEXT,
 precio NUMERIC(10,2),
 duracion INTEGER NOT NULL,
 imagen VARCHAR(255),
 estado VARCHAR(20) NOT NULL DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'No Disponible'))
);

CREATE TABLE horarios (
 id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 hora TIME UNIQUE
);

CREATE TABLE citas (
 id_cita INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
 id_servicio INTEGER NOT NULL REFERENCES servicios(id_servicio),
 id_horario INTEGER NOT NULL REFERENCES horarios(id_horario),
 empleado VARCHAR(140),
 fecha DATE NOT NULL,
 observaciones TEXT,
 estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Confirmada', 'En proceso', 'Finalizada', 'Cancelada', 'No asistio')),
 pago VARCHAR(20) NOT NULL DEFAULT 'No aplica' CHECK (pago IN ('SINPE', 'Efectivo', 'Tarjeta', 'No aplica')),
 fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(fecha, id_horario)
);

CREATE TABLE pedidos (
 id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
 numero_pedido VARCHAR(20) UNIQUE,
 direccion TEXT,
 metodo_pago VARCHAR(20) CHECK (metodo_pago IN ('SINPE', 'Efectivo')),
 tipo_entrega VARCHAR(10) NOT NULL DEFAULT 'envio' CHECK (tipo_entrega IN ('envio', 'retiro')),
 total NUMERIC(10,2),
 costo_envio NUMERIC(10,2) DEFAULT 0,
 observaciones TEXT,
 comprobante VARCHAR(255),
 estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Pagado', 'Preparando', 'Entregado', 'Cancelado')),
 fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE detalle_pedido (
 id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_pedido INTEGER REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
 id_producto INTEGER REFERENCES productos(id_producto),
 cantidad INTEGER,
 precio_unitario NUMERIC(10,2),
 subtotal NUMERIC(10,2)
);

CREATE TABLE pagos (
 id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 numero_pago VARCHAR(30) UNIQUE,
 id_pedido INTEGER NOT NULL REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
 metodo VARCHAR(30) NOT NULL DEFAULT 'SINPE Movil' CHECK (metodo IN ('SINPE', 'SINPE Movil', 'Efectivo', 'Tarjeta de Debito', 'Tarjeta de Credito')),
 monto NUMERIC(10,2),
 comprobante VARCHAR(255),
 referencia VARCHAR(100),
 observaciones TEXT,
 fecha_pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'En revision', 'Aprobado', 'Rechazado', 'Reembolsado'))
);

INSERT INTO administrador(nombre, usuario, correo, password, reset_token, reset_expires_at)
VALUES ('Administrador', 'admin', 'orlandogc2195@gmail.com', '$2y$10$CAMBIAR_HASH', NULL, NULL);

INSERT INTO categorias(nombre)
VALUES ('Shampoo'), ('Acondicionadores'), ('Tratamientos'), ('Tintes'), ('Barba'), ('Peinado'), ('Manicure'), ('Pedicure'), ('Accesorios');

INSERT INTO servicios(nombre, descripcion, precio, duracion)
VALUES
 ('Corte Caballero', 'Corte', 6000, 30),
 ('Corte Dama', 'Corte', 9000, 60),
 ('Barba', 'Perfilado', 4000, 20),
 ('Manicure', 'Servicio', 10000, 60),
 ('Pedicure', 'Servicio', 12000, 60),
 ('Balayage', 'Color', 65000, 180),
 ('Keratina', 'Tratamiento', 45000, 180);

INSERT INTO horarios(hora)
VALUES
 ('08:00:00'), ('08:30:00'), ('09:00:00'), ('09:30:00'),
 ('10:00:00'), ('10:30:00'), ('11:00:00'), ('11:30:00'),
 ('12:00:00'), ('12:30:00'), ('13:00:00'), ('13:30:00'),
 ('14:00:00'), ('14:30:00'), ('15:00:00'), ('15:30:00'),
 ('16:00:00'), ('16:30:00'), ('17:00:00'), ('17:30:00');

CREATE INDEX idx_contacto_correo ON contacto_mensajes(correo);
CREATE INDEX idx_contacto_creado_en ON contacto_mensajes(creado_en);
CREATE INDEX idx_producto_nombre ON productos(nombre);
CREATE INDEX idx_producto_categoria ON productos(id_categoria);
CREATE INDEX idx_citas_fecha ON citas(fecha);
CREATE INDEX idx_citas_fecha_estado ON citas(fecha, estado);
CREATE INDEX idx_pedidos_fecha_estado ON pedidos(fecha, estado);
CREATE INDEX idx_pagos_estado_fecha ON pagos(estado, fecha_pago);
CREATE INDEX idx_admin_reset_token ON administrador(reset_token);

CREATE OR REPLACE FUNCTION actualizar_fecha_producto()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
 NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
 RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_actualizar_fecha_producto
BEFORE UPDATE ON productos
FOR EACH ROW
EXECUTE FUNCTION actualizar_fecha_producto();

CREATE VIEW vw_productos AS
SELECT p.id_producto, p.codigo, p.nombre, c.nombre AS categoria,
       p.descripcion, p.precio, p.stock, p.estado
FROM productos p
JOIN categorias c ON p.id_categoria = c.id_categoria;

CREATE VIEW vw_servicios AS
SELECT id_servicio, nombre, descripcion, precio, duracion, estado
FROM servicios;

CREATE VIEW vw_citas AS
SELECT ci.id_cita, cl.nombre AS cliente, s.nombre AS servicio,
       h.hora, ci.fecha, ci.estado
FROM citas ci
JOIN clientes cl ON ci.id_cliente = cl.id_cliente
JOIN servicios s ON ci.id_servicio = s.id_servicio
JOIN horarios h ON ci.id_horario = h.id_horario;

CREATE VIEW vw_pedidos AS
SELECT p.id_pedido, c.nombre AS cliente, p.metodo_pago,
       p.total, p.estado, p.fecha
FROM pedidos p
JOIN clientes c ON p.id_cliente = c.id_cliente;

CREATE VIEW vw_pagos AS
SELECT pa.id_pago, c.nombre AS cliente, pe.id_pedido, pe.total,
       pa.metodo, pa.estado, pa.comprobante
FROM pagos pa
JOIN pedidos pe ON pa.id_pedido = pe.id_pedido
JOIN clientes c ON pe.id_cliente = c.id_cliente;
